services:
  frontend-web:
    container_name: sigue-adelante-radio-frontend
    image: sigue-adelante-radio:1.0.0
    build: .
    restart: 'on-failure'
    ports:
      - 5000:80
    networks:
      - sigue-adelante-radio
    

networks:
  sigue-adelante-radio:
    external: true